# Generated by Django 4.1.3 on 2022-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdescribe', models.CharField(max_length=1023)),
                ('centity1', models.CharField(max_length=255)),
                ('crelationship', models.CharField(max_length=64)),
                ('centity2', models.CharField(max_length=255)),
            ],
        ),
    ]
